---
title: "Data608_Project6"
author: "Jenny"
date: "April 30, 2018"
output: html_document
---

##### Read the data
```{r}
mydata <- read.csv(url("https://raw.githubusercontent.com/JennierJ/CUNY_DATA_608/master/Final_Project/Drinking_Water_Quality_Distribution_Monitoring_Data.csv"))
View(mydata)
```

##### Explore the data
```{r}
head(mydata)
summary(mydata)
```

##### Preliminary plots

```{r plot}
# pick a day 2015/01/01
mydata_01_01_2015 <- subset(mydata, mydata$Sample.Date == "01/01/2015")
View(mydata_01_01_2015)
# What are the residual free chlorine during the day on 01/01/2015?
plot(mydata_01_01_2015$Residual.Free.Chlorine..mg.L. ~ mydata_01_01_2015$Sample.Time)
# What are the turbidity during the day on 01/01/2015?
plot(mydata_01_01_2015$Sample.Time, mydata_01_01_2015$Turbidity..NTU.)
# Analyze the regression relationship between residual free chlorine and turbidity
liner <- lm(mydata_01_01_2015$Residual.Free.Chlorine..mg.L. ~ mydata_01_01_2015$Turbidity..NTU.)
liner
# Evaluate the quality of the model
summary(liner)
# Resudual Analysis
plot(fitted(liner), resid(liner))
qqnorm(resid(liner))
qqline(resid(liner))
```


